language: python  # language the project will be in
python:
  - "3.7" # version

services:
  - docker

before_script: pip install docker-compose

#Script to run before any execution commands
script:
  - docker-compose run app sh -c "python manage.py test && flake8"